# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 00:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bank_region', models.CharField(choices=[('Nigeria', 'Nigeria')], default='nigeria', max_length=10)),
                ('bank_account_number', models.CharField(max_length=10)),
                ('bank', models.CharField(choices=[('Access Bank', 'Access Bank'), ('Citibank', 'Citibank'), ('Diamond Bank', 'Diamond Bank'), ('Ecobank', 'Ecobank'), ('Fidelity Bank', 'Fidelity Bank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('First City Monument Bank', 'First City Monument Bank'), ('Guaranty Trust Bank', 'Guaranty Trust Bank'), ('Heritage Bank plc', 'Heritage Bank plc'), ('Keystone Bank Limited', 'Skye Bank'), ('Stanbic IBTC', 'Stanbic IBTC'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('Sterling Bank', 'Sterling Bank'), ('Union Bank', 'Union Bank'), ('United Bank for Africa', 'United Bank for Africa'), ('Unity Bank plc', 'Unity Bank plc'), ('Wema Bank', 'Wema Bank'), ('Zenith Bank', 'Zenith Bankk')], default='Guaranty Trust Bank', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
