# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
