# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sbdsellorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbdsellorder',
            old_name='ngn',
            new_name='sbd_ngn',
        ),
    ]
