# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180204_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbdsellorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sbdsellorder',
            name='sbd',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sbdsellorder',
            name='sbd_ngn',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sbdsellorder',
            name='sbd_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
