# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180205_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbdsellorder',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('Citibank', 'Citibank'), ('Diamond Bank', 'Diamond Bank'), ('Ecobank', 'Ecobank'), ('Fidelity Bank', 'Fidelity Bank'), ('First Bank of Nigeria', 'First Bank of Nigeria'), ('First City Monument Bank', 'First City Monument Bank'), ('Guaranty Trust Bank', 'Guaranty Trust Bank'), ('Heritage Bank plc', 'Heritage Bank plc'), ('Keystone Bank Limited', 'Skye Bank'), ('Stanbic IBTC', 'Stanbic IBTC'), ('Standard Chartered Bank', 'Standard Chartered Bank'), ('Sterling Bank', 'Sterling Bank'), ('Union Bank', 'Union Bank'), ('United Bank for Africa', 'United Bank for Africa'), ('Unity Bank plc', 'Unity Bank plc'), ('Wema Bank', 'Wema Bank'), ('Zenith Bank', 'Zenith Bankk')], max_length=50),
        ),
    ]
