# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180205_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbdsellorder',
            name='sbd_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
